apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: 676591241328.dkr.ecr.ap-northeast-2.amazonaws.com/fastapi-test-image:latest
          ports:
            - containerPort: 8000
